env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Device
    FOX_BRANCH: fox_11.0
    DT_LINK: https://github.com/OrangeFoxRecovery/device_samsung_f62.git
    DEVICE: f62
    OEM: samsung
    TARGET: recoveryimage

    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: OrangeFox*.zip

    # Extra Command
    EXTRA_CMD: git clone https://GitHub.com/TeamWin/android_vendor_twrp.git -b android_11 $SYNC_PATH/vendor/twrp

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Full (absolute) path. Use "$HOME" instead of "~".
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

    # Telegram
    TG_CHAT_ID: ENCRYPTED[0003e1cf5276424a5b2afb8c6a39f2d830864e8555b37220bd3bf173f3ef5b8769ab98425d96a76adf64b18241c940dd]
    TG_TOKEN: ENCRYPTED[03de4105db5d23ec42490965c0a0f79217c1e3366cb152bd9d9a045e22586eba675615e1f08bf1aea3e860d499efde60]

task:
  name: "Recovery Build"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash upload.sh
